### ISSUE TITLE
Not an editor command: Mason

### ISSUE THREAD

**Issue by accessd** [pgosar/CyberNvim#15]
After fresh installation, when I open nvim and type :Mason, it says `Not an editor command: Mason`
I discovered the same problem here: https://github.com/LazyVim/LazyVim/issues/1237
I've fixed it by adding `require('mason').setup()` to `user_config.lua`:

```
M.user_conf = function()
  vim.cmd([[
  autocmd VimEnter * lua vim.notify("Welcome to CyberNvim!", "info", {title = "Neovim"})]])
  require('mason').setup()
end
```

**Comment by pgosar** [comment]
Interesting, thanks for the issue. Haven't ran into this myself so if you could test and open a quick PR that would be great
