### ISSUE TITLE
failed to run config for mason-nvim-dap.nvim

### ISSUE THREAD

**Issue by insidesources** [pgosar/CyberNvim#8]
When launching i get this popup message:

![2024-01-05-115417_1105x270_scrot](https://github.com/pgosar/CyberNvim/assets/56140662/1a282007-8b77-413c-ba95-73a452d67856)

How do i fix this? I am using the custom config provided on the github page

**Comment by pgosar** [comment]
Fixed, was a problem in my personal config

**Comment by insidesources** [comment]
Confirmed working now, thank you!
