### ISSUE TITLE
User config can not override default options

### ISSUE THREAD

**Issue by h4m6urg1r** [pgosar/CyberNvim#9]
Title says it all. I tried overriding `expandtab` to `false` it did not work, I thought I missed something but when I tried disabling expand tab from default options part it worked as expected. I don't understand what might be the underlying reason but it just does not work by default. I also tried setting `numberwidth` to some arbitrary number (10) and it had no effect. Setting new options work though.

**Comment by pgosar** [comment]
Looks like I accidentally broke it a couple commits ago. Try updating CyberNvim and see if it works now

**Comment by h4m6urg1r** [comment]
It works now. Thanks.
